name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.21', '1.22']
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    
    - name: Install dependencies
      run: go mod download
    
    - name: Get headver version
      id: headver
      shell: bash
      run: |
        chmod +x scripts/headver.sh
        VERSION=$(scripts/headver.sh)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
    
    - name: Build
      run: |
        go build -ldflags "-X github.com/pyhub-kr/pyhub-sejong-cli/internal/cmd.Version=${{ steps.headver.outputs.version }} -X github.com/pyhub-kr/pyhub-sejong-cli/internal/cmd.GitCommit=${{ github.sha }} -X github.com/pyhub-kr/pyhub-sejong-cli/internal/cmd.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o sejong-${{ matrix.os }}-${{ matrix.go-version }} ./cmd/sejong
    
    - name: Test binary
      run: |
        ./sejong-${{ matrix.os }}-${{ matrix.go-version }} version
        ./sejong-${{ matrix.os }}-${{ matrix.go-version }} --help
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sejong-${{ matrix.os }}-go${{ matrix.go-version }}
        path: sejong-${{ matrix.os }}-${{ matrix.go-version }}*