name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.2534.1)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for changelog generation
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
    
    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        install-only: true
        version: latest
    
    - name: Get headver version
      id: headver
      run: |
        chmod +x scripts/headver.sh
        VERSION=$(scripts/headver.sh)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building release version: $VERSION"
    
    - name: Create temporary tag if workflow_dispatch
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag -a ${{ github.event.inputs.tag }} -m "Release ${{ github.event.inputs.tag }}"
    
    - name: Run GoReleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Set version from headver
        export VERSION=${{ steps.headver.outputs.version }}
        goreleaser release --clean